								if (typeof(document.getElementById("avaholder_63726")) == 'object') 
								{ 
									var el = document.getElementById('avaholder_63726');
									document.getElementById('avaholder_63726').innerHTML="     <div class='pr-AVA'> <table>  <tr class='pr-AVA-even pr-AVA-slogan'> <td colspan='3'> <span class='pr-AVA-slogan'>Предложения интернет-магазинов</span> </td> </tr>    <tr class='pr-AVA-odd'> <td>  <a href='http://ava.ua/product/514716/?p=406' target='_blank' class='pr-AVA-title'> <span class='pr-AVA-cat'>Мобильный телефон</span> Nokia 800 Lumia Gloss White </a>  </td>  <td> <a href='http://ava.ua/product/514716/?p=406' target='_blank' class='pr-AVA-price'>от 1 797 грн.</a> </td>  <td>  <a href='http://ava.ua/product/514716/?p=406' target='_blank' class='pr-AVA-shop'>в MobiDrive.com.ua и других..</a>  </td>   </tr>  <tr class='pr-AVA-even'> <td>  <a href='http://ava.ua/product/632916/?p=406' target='_blank' class='pr-AVA-title'> <span class='pr-AVA-cat'>Мобильный телефон</span> Nokia Lumia 820 Black </a>  </td>  <td> <a href='http://ava.ua/product/632916/?p=406' target='_blank' class='pr-AVA-price'>от 2 982 грн.</a> </td>  <td>  <a href='http://ava.ua/product/632916/?p=406' target='_blank' class='pr-AVA-shop'>в МОБИЛЛАК и других..</a>  </td>   </tr>  <tr class='pr-AVA-odd'> <td>  <a href='http://ava.ua/product/568915/?p=406' target='_blank' class='pr-AVA-title'> <span class='pr-AVA-cat'>Мобильный телефон</span> Мобильный телефон Nokia 808 PureView Black </a>  </td>  <td> <a href='http://ava.ua/product/568915/?p=406' target='_blank' class='pr-AVA-price'>от 3 382 грн.</a> </td>  <td>  <a href='http://ava.ua/product/568915/?p=406' target='_blank' class='pr-AVA-shop'>в AKS.ua и других..</a>  </td>   </tr>  </table> </div>  <div align='right' class='pr-AVA-conteiner'> <a href='http://ava.ua?p=406' target='_blank' class='pr-AVA-add'>Торговый центр <img src='http://ava.ua/favicon.ico' width='16' height='16'></a> </div>   ";
									
									var ss1 = document.createElement('style');
									var def = " .pr-AVA * { 	margin:0!important; 	padding: 0!important; 	font: 11px/1.2 Tahoma !important; }  .pr-AVA-even td{background-color:#FDF9E1!important} .pr-AVA-odd td{background-color:#E8F4BA!important}  .pr-AVA a{color:#666!important;text-decoration:none!important;font-size:12px!important} .pr-AVA a:hover{text-decoration:underline!important} .pr-AVA table{width:100%!important;border-collapse:collapse} .pr-AVA table td{vertical-align:top!important;text-align:left!important;padding:5px 10px!important;border:1px solid #fff!important}  .pr-AVA .pr-AVA-slogan{color:#686868!important; font-weight:bold !important; font-size:14px!important;} .pr-AVA-slogan{}  .pr-AVA .pr-AVA-cat {display: inline-block!important; vertical-align: text-top;} .pr-AVA .pr-AVA-title, .pr-AVA .pr-AVA-cat { color:#006699!important; font-weight:bold !important; } .pr-AVA .pr-AVA-price{color:#f00!important; font:bold 12px Arial,sans-serif!important; white-space:nowrap} .pr-AVA .pr-AVA-shop{font-weight:bold!important}  .pr-AVA-conteiner { margin: 1px 0px 2px 0px;  } .pr-AVA-add { color: #006699 !important; font: 10px/12px Tahoma !important; }  .pr-AVA-conteiner { margin: 1px 0px 2px 0px;  } .pr-AVA-add { color: #069 !important; font: 11px/14px Tahoma !important; text-decoration: none!important; margin-right: 5px; } .pr-AVA-add img { border: none; vertical-align: bottom; }   .pr-AVA-even td{background-color:#F2F4F5!important}  .pr-AVA-odd td{background-color:#E5E8EA!important}    .pr-AVA a{color:#666!important;text-decoration:none!important;font-size:12px!important}  .pr-AVA a:hover{text-decoration:underline!important}    .pr-AVA table td {      border: none !important;      padding: 2px 10px !important; }    .pr-AVA .pr-AVA-slogan{color:#484848!important; font-weight:bold !important; font-size:13px!important;}  .pr-AVA .pr-AVA-shop{font-weight:bold!important}  .pr-AVA .pr-AVA-title { color:#006699!important; font-weight:bold !important; }  .pr-AVA .pr-AVA-price{color:#b00!important; font:bold 12px Arial,sans-serif!important; white-space:nowrap}";
									ss1.setAttribute("type", "text/css");
									if (ss1.styleSheet) {   
										ss1.styleSheet.cssText = def;
									} else {                
										var tt1 = document.createTextNode(def);
										ss1.appendChild(tt1);
									};
									var hh1 = document.getElementsByTagName('head')[0];
									hh1.appendChild(ss1);
								};
